### ISSUE TITLE
Trait Laravel\Nova\Fields\Expandable not found

### ISSUE THREAD

**Issue by lluisandreu** [waynestate/nova-ckeditor4-field#10]
Hello!

I get trait Laravel\Nova\Fields\Expandable not found. I think Nova is not using this Trait anymore?

Thanks.

**Comment by chrispelzer** [comment]
I just tried it out on Laravel Nova v1.2.1 and the trait is located at `vendor/laravel/nova/src/Fields/Expandable.php`.

Can you check your vendor folder for the above file to verify that it is there?

**Comment by lluisandreu** [comment]
Thanks for your quick response, 

The Trait is not there but I have no clue of what version of Nova I am using as it shows like "*" version in composer. How do you do it?

Thanks.

**Comment by lluisandreu** [comment]
I have Laravel Nova 1.0.17, sorry. I close the issue.
