### ISSUE TITLE
Additional plugins ?

### ISSUE THREAD

**Issue by ehben83** [waynestate/nova-ckeditor4-field#14]
Hi,
first, thanks for the package ! 

This is a question but can't find the tag to make it so :
Is there a way to add other plugins ?

Would like to add this one for example : https://ckeditor.com/cke4/addon/wordcount but don't know in which folder to place the files ? it's supposed to go to "ckeditor/plugins/"

**Comment by chrispelzer** [comment]
Since it looks like the WordCount plugin is not part of the default [CKEditor presets](https://ckeditor.com/cke4/presets-all)

You'll more than likely need to setup your own CKEditor fork to add those plugins with and use composer to pull it into your application.
You can find more information about doing that at https://github.com/waynestate/nova-ckeditor4-field/wiki/Using-Composer-for-Custom-CKEditor-Instance

**Comment by jeffcaulfield-morphsites** [comment]
I recently needed to customise CKEditor to prevent it from mangling copy-pasted markup and also include the [codemirror|https://ckeditor.com/cke4/addon/codemirror] plugin. The following did the job without having to fork any repos.

1. Add the plugin source via `yarn add ckeditor-codemirror-plugin` or similar.
2. Add something like the following to `webpack.mix.js` (or equivalent) to copy the needed files to the `js/vendor` public folder.
```javascript
mix.copyDirectory('node_modules/ckeditor-codemirror-plugin/codemirror', 'public/js/vendor/codemirror')
```
3. Create `ckeditor.js` in `public/vendor/nova` with content like the following (adapt to suit your needs).
```javascript
(function () {
    if (CKEDITOR) {

        // enable external plugins here
        CKEDITOR.plugins.addExternal('codemirror', '/js/vendor/codemirror/');

        // adjust CKEditor behaviour to prevent mangling of complex markup
        CKEDITOR.on('instanceReady', function(ev) {

            var writer = ev.editor.dataProcessor.writer;

            writer.indentationChars = '\t';

            writer.setRules('p', {
                indent: true,
                breakBeforeOpen: true,
                breakAfterOpen: false,
                breakBeforeClose: false,
                breakAfterClose: true
            });

            writer.setRules('div', {
                indent: true,
                breakBeforeOpen: true,
                breakAfterOpen: true,
                breakBeforeClose: true,
                breakAfterClose: true
            });

        });

        CKEDITOR.dtd.$removeEmpty['i'] = false;
        CKEDITOR.dtd.a.div = true;
        CKEDITOR.dtd.a.p = true;

        CKEDITOR.config.autoParagraph = false;

    }
})();
```
4. In your `NovaServiceProvider::boot` method, inject the above script **after** the call to `parent::boot()` such that the `nova-ckeditor` script loads before this one.
```php
    public function boot()
    {
        parent::boot();

        // this must occur AFTER parent::boot()
        Nova::serving(function (ServingNova $event) {
            Nova::script('ckeditor-codemirror-plugin', __DIR__ . '/../../public/vendor/nova/ckeditor.js');
        });
    }
```
5. Finally, enable the plugin in `config/nova/ckeditor-field.php`.
```php
<?php
return [

    'options' => [

        // ...

        'extraPlugins' => 'codemirror',

        // ...

    ],

    // ...

];
```

This saved me a lot of hassle so I thought I'd share it with other users of this fine component. :-)

**Comment by chrispelzer** [comment]
Thanks @jeffcaulfield-morphsites!

I added the information as part of the Wiki at
https://github.com/waynestate/nova-ckeditor4-field/wiki/Adding-additional-plugins

**Comment by cgarofalo** [comment]
Thanks @jeffcaulfield-morphsites for the info. What would I need to do if I wanted to create my own plugin, and not install one using yarn? It's not a plugin I'd want to release, so I wouldn't want to upload a package to the general public. I want to do something very simple. I want to add a button that add some pre formatted HTML. That's all. Thanks!!

**Comment by jeffcaulfield-morphsites** [comment]
Hi @cgarofalo. As long as your plugin files make it into the `js/vendor/` public folder, I think steps 3-5 should still work (replacing "codemirror" with your own plugin name and skipping the bits of Javascript you don't need, of course). Hope that helps. 😄

**Comment by cgarofalo** [comment]
@jeffcaulfield-morphsites It does! Thank very much.

**Comment by zgetro** [comment]
@jeffcaulfield-morphsites  Thanks for solution. before i read your comments or wiki i found another way to achive same. in my case i wanted to use [Uploadcare](https://github.com/uploadcare/uploadcare-ckeditor)  
follow steps to achive that.

1. [Build ckeditor](https://ckeditor.com/cke4/builder) as per your requirment  from official site.

2.  Unzip build to [Laravel Project]/public/js/.

3. replace ckeditor_url under the published config config/nova/ckeditor-field.php to be

`'ckeditor_url' => config('app.url').'/js/ckeditor/ckeditor.js',`

4. all your addtional configration is set to [config/nova/ckeditor-field.php ](https://github.com/waynestate/nova-ckeditor4-field#configuration-options)

PS: you can host your `ckeditor_url` to some where else if you using Vapor or Headless laravel insted of puting them into public directory of your project.
