### ISSUE TITLE
Toolbar - List style

### ISSUE THREAD

**Issue by piep14** [waynestate/nova-ckeditor4-field#20]
I did not find the option in the package to handle lists such as "style". I want to delete the h1 tag. Thank you

**Comment by chrispelzer** [comment]
The issues should only be for issues with integrating the nova field with CKEditor. Any CKEditor implementation questions outside of integrating with Laravel Nova should be asked to the CKEditor issues or refer to the CKEditor docs for information on customizing CKEditor.
