### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by lluisandreu** [waynestate/nova-ckeditor4-field#21]
Is there a way to create custom styles?

Thanks.

**Comment by chrispelzer** [comment]
Which styles would you want to customize? The CKEditor WYSIWYG theme or adding additional style for the site the content is being used on?

You can use a custom CKEditor using the information at
https://github.com/waynestate/nova-ckeditor4-field/wiki/Using-Composer-for-Custom-CKEditor-Instance
