### ISSUE TITLE
help() option does not work

### ISSUE THREAD

**Issue by ksorbo** [waynestate/nova-ckeditor4-field#22]
It seems as if the help() method does not work on CKEditor

`            CKEditor::make('Survey Instructions', 'survey_instructions')
                ->help('These instructions will be printed as the first page of the survey'),`
            
`             Number::make('Price', 'price')
                ->help('Enter price in US Dollars'),`

The help appears in the second case, does not appear in the first case

**Comment by chrispelzer** [comment]
@ksorbo If you update to 0.4.0, it will now use the default field component, which includes the ability of the help instead of relying on its own layout.

**Comment by tungvn** [comment]
@chrispelzer Using 0.7.0 but the help text is not showing.

**Comment by piotrh052b** [comment]
Any chances to fix it ?
