### ISSUE TITLE
The editor is not initialized on fields with the same name

### ISSUE THREAD

**Issue by f-liva** [waynestate/nova-ckeditor4-field#27]
By declaring two fields with the same label but with different identifiers, CKEditor is instantiated using the label instead of the identifier, thus generating console errors and not loading the editor at the second instance.

```php
public function fields(Request $request)
{
    return [
        CKEditor::make('Field Name', 'field_1'),
        CKEditor::make('Field Name', 'field_2'),
    ];
}
```

Opening console you can see this error:

`The editor instance "Field Name" is already attached to the provided element.`

And the second editor was not loaded.

**Comment by chrismackie28** [comment]
I also have this issue when using spatie/nova-translatable as it creates duplicate fields for different locales.

**Comment by chrispelzer** [comment]
This should now be fixed. I changed it to use the `field.attribute` instead of `field.name`.

I tested it out with spatie/nova-translatable and it works correctly.
