### ISSUE TITLE
Integrate "Upload Image" plugin for Media

### ISSUE THREAD

**Issue by ghost** [waynestate/nova-ckeditor4-field#4]
how did you upload the image? the link?
I didn't find a way to upload a photo from my computer

**Comment by chrispelzer** [comment]
Currently there is no media library/upload ability set up right now.

Images are only available using a URL to the image right now.

I am looking into getting the [CKFinder](https://ckeditor.com/cke4/addon/ckfinder) set up since there is a [CKFinder Laravel Package](https://github.com/ckfinder/ckfinder-laravel-package) for it.

**Comment by chrispelzer** [comment]
Since CKFinder is a paid service, we'll just need to rely on the Image Upload plugin.
https://ckeditor.com/cke4/addon/uploadimage

**Comment by iHazzam** [comment]
+1 looking forward to this feature will be useful

**Comment by thierry2015** [comment]
+1

**Comment by timvandijck** [comment]
CKFinder is actually easy to integrate, here's some reference code I used once:
`
ClassicEditor
            .create( document.querySelector( '#editor' ), {

                toolbar: [ 'heading', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'image'],
                image: {
                    toolbar: [ 'imageTextAlternative', '|', 'imageStyle:full', 'imageStyle:side' ]
                },
                ckfinder: {
                    uploadUrl: '/admin/image-upload'
                }
            } )
`

The upload endpoint is handled by this code:
`
class ImageController extends Controller {
    public function upload(Request $request) {
        $path = $request->file('upload')->store('wysiwyg_images', 'public');

        return response()->json([
            'uploaded' => true,
            'url' => env('APP_URL') . Storage::url($path)
        ]);
    }
}
`

I suspect people could also just add a custom route to the configuration options (https://github.com/waynestate/nova-ckeditor4-field#customization) and handle the upload themselves for now.

**Comment by piep14** [comment]
I failed to add the image upload directly into CKeditor, did you succeed? Thank you

**Comment by Atnaize** [comment]
If you don't need to retrieve images from other sources you can also just copy/paste images to the ckeditor.

It will encode the image in a base 64 format and store it directly in the database. If you tend to have a lot of large images, I recommend you to use larger fields value (MEDIUMTEXT) in your database.
