### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by jaros93** [waynestate/nova-ckeditor4-field#58]
Added Nova 4 compatibility.

**Comment by billyjustal** [comment]
+1

**Comment by aliwesome** [comment]
any updates? 👀

**Comment by itrack** [comment]
+1

**Comment by worthers** [comment]
+1 Please update for Nova 4 🙏  thanks.

**Comment by chrispelzer** [comment]
the update process has been started today, can't give a timeline but soon.

**Comment by chrispelzer** [comment]
I just released v1.0.0

This brings in support for Nova v4 as well as removes it's dependency on outside packages for getting CKEditor into Vue3 since there isn't anymore and the official CKEditor vue component is now only avaialble for vue2 where as the CKeditor5 is vue3 compatible.
