### ISSUE TITLE
Possible to add codesnippet

### ISSUE THREAD

**Issue by nikkanetiya** [waynestate/nova-ckeditor4-field#6]
Thanks for this helpful package. I just need to ask, if it there is a quick way to add CKEditor plugin for codesnippet.

**Comment by chrispelzer** [comment]
The code snippet is included with the default CKEditor that is used. Currently the default CKEditor 4 that is being used is the "Standard-All". 

You can review which plugins are available with each version at 
https://ckeditor.com/cke4/presets-all

Instructions how to structure the CDN URL is at https://cdn.ckeditor.com/

You'll need to add the options for `extraPlugins` and the `toolbar` to include the CodeSnippet plugin.

```
            CKEditor::make('Body', 'body')
                ->options([
                    'extraPlugins' => 'codesnippet',
                    'toolbar' => [
                        ['Source','-','CodeSnippet'],
                    ]
                ]);
```

**Comment by nikkanetiya** [comment]
@chrispelzer Thanks, Keep up the good work.

**Comment by iHazzam** [comment]
Alternatively, there is no need to use a CDN if you don't want - You can locally install the exact build of CkEditor and point the config file at it, that way you can control your own plugins.

`'ckeditor_url' => env('APP_URL') . '/ckeditor/ckeditor.js',`
