### ISSUE TITLE
Mathjax plugin

### ISSUE THREAD

**Issue by nietopablo19** [waynestate/nova-ckeditor4-field#74]
Hi, I am not able to activate the [mathjax](https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html) plugin. 

I tried in 2 different ways:

1.  With [Adding additional plugins wiki](https://github.com/waynestate/nova-ckeditor4-field/wiki/Adding-additional-plugins). Here i wasn't able to find the npm package, so i downloaded and copied the plugin directly to the `public/js/vendor` folder, once I finished all the steps, i got the following error: 

<img width="959" alt="Screenshot 2022-11-04 at 19 25 36" src="https://user-images.githubusercontent.com/15250628/200048613-407bbbd7-d368-431a-98c3-ffd55da0780d.png">

The [documentation](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#mathjax-no-config) says that the mathjaxlib config wasn't set, which leads me to try to implement it as indicated in the ckeditor documentation (way 2)

2. Simply added the following parameters to the configuration: 
```
'options' => [
        // ....
        'extraPlugins' => 'mathjax',
        'mathJaxLib' => 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML',
        'mathJaxClass' => 'ik-equation',
    ],

```
In this case the plugin is properly fetched from the cdn

<img width="643" alt="Screenshot 2022-11-04 at 19 39 03" src="https://user-images.githubusercontent.com/15250628/200051024-02976726-c097-48ae-9bd9-c2866fd1b6a9.png">

There is no error in the console. I can explore the CKEDITOR object and see that the plugin is there.

<img width="881" alt="Screenshot 2022-11-04 at 19 20 49" src="https://user-images.githubusercontent.com/15250628/200049850-edc465e3-7a64-4687-ad3c-b41d99710edd.png">

But unfortunately no widget is added to the component. 

Could you help me to understand what i am doing wrong? 

Many thanks in advance

**Comment by chrispelzer** [comment]
@nietopablo19 Just want to make sure, was it due to a misconfiguration?
