### ISSUE TITLE
How to add the image2 as an Additional plugins in this package?

### ISSUE THREAD

**Issue by divya-kanak** [waynestate/nova-ckeditor4-field#76]
Hello!

I'm working with Nova 4 and integrated this package as an editor in one of my post modules.

Now, I need to integrate the below upload image plugin in CKeditor :+1: 

https://ckeditor.com/cke4/addon/image2

I've followed this solution but didn't get the upload option in image pop up

https://github.com/waynestate/nova-ckeditor4-field/wiki/Adding-additional-plugins

can anyone please guide me on this?

@chrispelzer @robertvrabel @f-liva @dsampaolo @shaffe-fr @harrymessenger

**Comment by chrispelzer** [comment]
Hi @divya-kanak 

Since this is more of a discussion than issue, could you please recreate it over at the Discussions area?
https://github.com/waynestate/nova-ckeditor4-field/discussions
