### ISSUE TITLE
Page detail display data incorrect format 

### ISSUE THREAD

**Issue by davinyoeun** [waynestate/nova-ckeditor4-field#89]
1. Go to index page
2. Click on view detail
3. See the content

<img width="1177" alt="Screenshot 2023-08-24 at 2 55 54 PM" src="https://github.com/waynestate/nova-ckeditor4-field/assets/129028087/068a4fd3-156d-494a-88cc-f3e786001e6d">

**Comment by chrispelzer** [comment]
New 1.2.4 release fixes this issue, https://github.com/waynestate/nova-ckeditor4-field/releases/tag/1.2.4
