### ISSUE TITLE
Content edited in Source view not saving.

### ISSUE THREAD

**Issue by brandonjbegle** [waynestate/nova-ckeditor4-field#90]
Edits from 'Source' are not working. Only edits made in the WYSIWYG editor are persisted. If you edit the source and then make changes in the WYSIWYG, it saves as expected.

1. Click Source Button
2. Change content
3. Save Nova Resource

**Expected behavior**
Save content

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 116.0.5845.187

**Comment by chrispelzer** [comment]
New 1.2.4 release fixes this issue, https://github.com/waynestate/nova-ckeditor4-field/releases/tag/1.2.4
