### ISSUE TITLE
Add dependsOn method

### ISSUE THREAD

**Issue by tmartty** [waynestate/nova-ckeditor4-field#93]
Is it possible to add the new Dependent Fields method `dependsOn` to this CKEditor field?

Docs: https://nova.laravel.com/docs/resources/fields.html#dependent-fields

**Comment by chrispelzer** [comment]
Yep, I should be able to get that added and available soon.
https://nova.laravel.com/docs/customization/fields.html#dependent-form-field

**Comment by chrispelzer** [comment]
@tmartty Go ahead and try it now, I bumped it up to version 1.3.0 since it is changing the FormField to DependentFormField to prevent any issues with people updating.

**Comment by tmartty** [comment]
@chrispelzer works like a charm, thanks!

**Comment by HassanElshazlyEida** [comment]
@chrispelzer @tmartty I have tested it with version [2.0.0](https://github.com/waynestate/nova-ckeditor4-field/releases/tag/2.0.0) and not work

**Comment by chrispelzer** [comment]
@HassanElshazlyEida 

I'll verify it all. Are you currently using the latest version of Nova?

**Comment by HassanElshazlyEida** [comment]
Yes, I'm using Nova 5 

```
   "laravel/nova": "^5.0",
 `"waynestate/nova-ckeditor4-field": "^2.0",`
```
you can check my snippet also

 ```
           Select::make('Answer Type', 'answer_type')
                ->options([
                    AnswerTypeEnum::ALPHABET->value => 'Alphabet',
                    AnswerTypeEnum::NUMERIC->value => 'Numeric',
                    AnswerTypeEnum::TEXT_PHOTO->value => 'Text or Photo',
                ])->default(AnswerTypeEnum::TEXT_PHOTO->value)
                
                ->rules('required'),


            CKEditor::make('Answer Body', 'answer_body')
                ->dependsOn(['answer_type'], function (CKEditor $field, NovaRequest $request, FormData $formData) {
     
                    $field->show(); // testing 
                    // if ($formData->answer_type === AnswerTypeEnum::TEXT_PHOTO->value) {
                    //     $field->show();
                    // } else {
                    //     $field->hide();
                    // }
                }),

```

**Comment by HassanElshazlyEida** [comment]
maybe the problem with external package that I use which **"nova-flexible-content"**, see this [issue ](https://github.com/whitecube/nova-flexible-content/issues/524) @chrispelzer

**Comment by chrispelzer** [comment]
> maybe the problem with external package that I use which **"nova-flexible-content"**, see this [issue ](https://github.com/whitecube/nova-flexible-content/issues/524) [@chrispelzer](https://github.com/chrispelzer)

I'm going to guess that is the case since it seems to be altering the way that dependent fields work.

Using the code that you provided but with a more local approach, it seemed to be working fine with the current dependsOn

```
Select::make('Answer Type', 'answer_type')
  ->options([
      'Alphabet' => 'Alphabet',
      'Numeric' => 'Numeric',
      'Text or Photo' => 'Text or Photo',
  ])
  ->default('Text or Photo')
  ->rules('required'),


CKEditor::make('Answer Body', 'answer_body')
    ->dependsOn(['answer_type'], function (CKEditor $field, NovaRequest $request, FormData $formData) {
        if ($formData->answer_type === 'Text or Photo') {
            $field->show();
        } else {
            $field->hide();
        }
    }),
```
